services:

  postgres:
    image: postgres:17
    container_name: classfit-postgres

    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    volumes:
      - postgres-data:/var/lib/postgresql/data


    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10


  app:
    build: .
    container_name: classfit-app

    depends_on:
      postgres:
        condition: service_healthy

    env_file:
      - .env

    environment:
      DB_HOST: postgres
      DB_PORT: 5432

    ports:
      - "8080:8080"


volumes:
  postgres-data: